use parser::token::Token;

use crate::value::Value;

#[derive(Debug, Clone, PartialEq)]
pub enum BytecodeInstruction {
    // Stack operations
    Push(Value),
    Pop,

    // Function calls
    Call {
        /// Function to call, which can be a built-in function or a user-defined function.
        /// If the option is None, it means the function to call is on top of the stack and needs to be evaluated first.
        /// 
        /// NOTE: Lambdas will never have none here, will be given a unique identifier instead, so that they can be called by name.
        function: Option<Box<str>>,
        /// How many arguments to pop from the stack and pass to the function
        argc: usize,
    },

    // Definitions
    Define {
        /// Name of the variable or function being defined
        name: Box<str>,
        /// Value to assign to the variable or function being defined
        value: Value
    },

    // Define a function with the given name and bytecode. This is used for both named functions and lambdas, which will be given an autogenerated name.
    // This is a special form only for functions/lambdas. The rest must use the Define instruction.
    DefineFunction {
        /// Name of the variable being defined
        name: Box<str>,
        /// Names of the function's parameters, which will be used to bind the arguments passed to the function when it is called. The order of the parameters in this list corresponds to the order of the arguments passed to the function.
        args: Vec<Box<str>>,
        /// Optional name of the variadic parameter, which will be used to bind any extra arguments passed to the function when it is called. If this is None, then the function does not accept variadic arguments and an error should be raised if extra arguments are passed.
        variadic_arg: Option<Box<str>>,
        /// Bytecode to assign to the variable being defined
        bytecode: Vec<BytecodeInstruction>,
    },

    /// Undefine a variable or function, removing it from the current scope.
    Undefine {
        /// Name of the variable or function being undefined
        name: Box<str>,
    },

    /// If condition is true, execute then_branch, otherwise execute else_branch (if it exists)
    If {
        condition: Vec<BytecodeInstruction>,
        then_branch: Vec<BytecodeInstruction>,
        else_branch: Vec<BytecodeInstruction>,
    },

    /// Cond bytecode instruction, which evaluates each condition in order and executes the corresponding branch for the first true condition. If no conditions are true, executes the else_branch (if it exists).
    Cond {
        conditions: Vec<Vec<BytecodeInstruction>>,
        branches: Vec<Vec<BytecodeInstruction>>,
        else_branch: Option<Vec<BytecodeInstruction>>,
    },
}
